# Generated by Django 5.2.8 on 2025-11-20 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato +1XXXXXXXXX (10 dígitos después del +1).', regex='^\\+1\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener el formato +1XXXXXXXXX (10 dígitos después del +1).', regex='^\\+1\\d{10}$')]),
        ),
    ]
